### ISSUE TITLE
Can't create a new Campaign

### ISSUE THREAD

**Issue by Dauron24** [worldanvil/worldanvil-bug-tracker#190]
Dauron

 Campaign:

Create a new Campaign: 

https://www.worldanvil.com/heroes/campaign/new:

 I have deleted all my old Campaign, and now I can't crate a new Campaign. I am a free user.

1. I go to the "new Campaign" open.
2. Fill the "Campaign Name"
3. Choose an RPG System.
4. Click on save changes

And The result is, 

This gamemaster has been quite naughty. You will need to upgrade your membership to create more campaigns!

**Expected behavior**
To create a new Campaign

**Comment by Kordishal** [comment]
After deleting a campaign no world is selected. Select a world to create a new campaign.

**Comment by Dauron24** [comment]
I don't understand. 

Where is the option, to choose the World. 
![New Campain](https://user-images.githubusercontent.com/29235468/115863013-24a5ce00-a435-11eb-8968-6171bb52e2a2.PNG)

And I think, that wen I choose to create a Campaign, that would implied the world. 
![Select World and new Campagin](https://user-images.githubusercontent.com/29235468/115863197-6cc4f080-a435-11eb-80c3-baae9671db0b.PNG)

**Comment by Kordishal** [comment]
Ah, you do not have a world at all then. You need a world to make a campaign

**Comment by Dauron24** [comment]
What do you mean, 

You can see, that I have a World. 
![Select World and new Campagin](https://user-images.githubusercontent.com/29235468/115869188-d2b57600-a43d-11eb-91b6-52f66ee0ec3b.PNG)

And even when I went to create a campaign over the World screen. I can't
![alternative](https://user-images.githubusercontent.com/29235468/115869336-042e4180-a43e-11eb-8be8-21463338abee.PNG)

**Comment by Kordishal** [comment]
Campaign creation & deletion needs to be more streamlined to be clearer when they can be made.

Can you try making a campaign that is just the title `test`and the first RPG feature selected?

**Comment by Dauron24** [comment]
No, It doesn't work.

And I have tried this before. Whit and selected RPG system

**Comment by Kordishal** [comment]
Well, I am not sure what else could be wrong. I can't reproduce the conditions you have on my test account, unfortunately. Can you try to make a second world and create a campaign for that one?

**Comment by iamromeo** [comment]
At this point, free accounts have access to 2 campaigns, including ARCHIVED campaigns. I can see from your account that there are currently 2 archived campaigns in system waiting for deletion.

**Comment by iamromeo** [comment]
This is fixed will be deploying shortly

**Comment by iamromeo** [comment]
@Kordishal fixing this also fixed the bug that caused the wrong detection of if a world is currently active in otder to allow for a campaign to be created.

**Comment by Dauron24** [comment]
The error message has changed. It tells me straight away that I won't create a new company anymore.

Only the archived campaigns are apparently still not deleted. And I have no idea how I can delete archived campaigns.
